### ISSUE TITLE
How it works section issue with bigger screens

### ISSUE THREAD

**Issue by fmmricardo** [almeiduh/vejo-em-casa-fe#14]
There are some issues with this section when we open the page in bigger screens:

![Screenshot 2020-03-30 at 08 51 18](https://user-images.githubusercontent.com/20669868/77888327-fcfd2a00-7263-11ea-8df9-a6391c0da453.png)

**Comment by michkin** [comment]
I think it's resolved, can you check?

**Comment by fmmricardo** [comment]
Nice job 👍
